#!/usr/bin/env bash
# This script configures a web server to include a custom response header with the server's hostname

# Install Nginx if not installed
sudo apt update -y
sudo apt install -y nginx

# Add a custom header to the Nginx configuration
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        add_header X-Served-By \"\$hostname\";
        try_files \$uri \$uri/ =404;
    }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Restart Nginx to apply changes
sudo systemctl restart nginx
