#!/usr/bin/env bash
# This script configures a new Ubuntu server to add a custom HTTP response header

# Update and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Add custom HTTP response header
sudo sed -i '/http {/a \    add_header X-Served-By $hostname;' /etc/nginx/nginx.conf

# Restart Nginx to apply changes
sudo systemctl restart nginx
